//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Donations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("August2008.Resources.Donations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal is a global e-commerce business allowing payments and money transfers to be made through the Internet. Online money transfers serve as electronic alternatives to paying with traditional paper methods, such as checks and money orders..
        /// </summary>
        public static string AboutPayPal {
            get {
                return ResourceManager.GetString("AboutPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose desired amount and click on PayPal button....
        /// </summary>
        public static string ChooseAndDonate {
            get {
                return ResourceManager.GetString("ChooseAndDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Message.
        /// </summary>
        public static string CommentPopupTitle {
            get {
                return ResourceManager.GetString("CommentPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In memory of Georgian heroes who died in Russia-Georgia War of August 2008.
        /// </summary>
        public static string DonationCause {
            get {
                return ResourceManager.GetString("DonationCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditYourComment {
            get {
                return ResourceManager.GetString("EditYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გმადლობთ.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უღრმეს მადლობას გიხდით 2008 წლის სამამულო ომში დაღუპულ გმირთა ოჯახების თანადგომისთვის.
        ///
        ///თუ რაიმე შეკითხვა გაქვთ ან უბრალოდ გსურთ რომ გამოგვეხმაუროთ, გთხოვთ გამოიყენოთ ჩვენი &lt;a href=&quot;{0}&quot;&gt;საკონტაქტო გვერდი&lt;/a&gt; ან იხილოთ ხშირად &lt;a href=&quot;{1}&quot;&gt;დასმული კითხვების სია&lt;/&gt;.
        ///
        ///ბედნიერ დღეს გისურვებთ...
        ///.
        /// </summary>
        public static string ThankYouDisplayMessage {
            get {
                return ResourceManager.GetString("ThankYouDisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოგესალმებით.
        ///
        ///უღრმეს მადლობას გიხდით 2008 წლის სამამულო ომში დაღუპულ გმირთა ოჯახების თანადგომისთვის.
        ///
        ///www.august2008.org 
        ///ადმინისტრაცია.
        /// </summary>
        public static string ThankYouEmailMessage {
            get {
                return ResourceManager.GetString("ThankYouEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to make a donation, you must be registered.. Please go to the &lt;a href=&quot;{0}&quot;&gt;registration&lt;/a&gt; page and sing up using your OpenID. .
        /// </summary>
        public static string YouMustBeRegistered {
            get {
                return ResourceManager.GetString("YouMustBeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You message.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
    }
}
